### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RohanAlexander** [yulexun/2024uselectionprediction#23]
Can you please fix typos:
- `### States included in anaylsis`
- `#| fig-cap: Historical State Voting Trends Are Maintined in 2024`
- `#| fig-cap: Both Canidate Percentages Are Gaining Support Closer to the Election`
- Next, we set up a bayesian model as the following in accordance to @sec-modelsetup: - should be "Bayesian"
- `#| fig-cap: "The MLR Model Accruatley Predicts the Testing Dataset"`
- `#| fig-cap: "Kamala Harris is Predicted to get Approximatley 52% of Popular Vote"`
- `# Overview of American Electon System`
- `#| fig-cap: Donald Trump Expected to Recieve Approximatley 45% of the Vote`

And reduce the number of decimal places in Tables 2 and 3.

Force the date on the paper to be yesterday, otherwise when you re-render it will update to whenever you re-render but you're not doing anything that affects the forecasts so it shouldn't change.

**Comment by yulexun** [comment]
Hi Rohan, thanks so much for the suggestion, we have updated the typo and forced the date to yesterday in our latest commit. 
Here is the link to the latest commit: [https://github.com/yulexun/2024uselectionprediction/commit/ab5506bbaf277f93fc6bb74d603c2782d4428a06](https://github.com/yulexun/2024uselectionprediction/commit/ab5506bbaf277f93fc6bb74d603c2782d4428a06)

**Comment by RohanAlexander** [comment]
Thank you. Can I use as an example please?
